# Generated by Django 2.0.5 on 2018-07-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('leader', models.CharField(max_length=100)),
                ('member', models.CharField(max_length=100)),
                ('membertag', models.CharField(max_length=100)),
                ('member2', models.CharField(max_length=100)),
                ('member2tag', models.CharField(max_length=100)),
                ('member3', models.CharField(max_length=100)),
                ('member3tag', models.CharField(max_length=100)),
                ('member4', models.CharField(max_length=100)),
                ('member4tag', models.CharField(max_length=100)),
                ('member5', models.CharField(max_length=100)),
                ('member5tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_record',
            name='team',
        ),
        migrations.RemoveField(
            model_name='user_record',
            name='username',
        ),
        migrations.AddField(
            model_name='user_record',
            name='name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='user_record',
            name='tag',
            field=models.CharField(default='usertag', max_length=300),
        ),
    ]
